spring:
  application:
    name: ticketing_System
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@ticketingsystem.t4kfl.mongodb.net/SystemData?retryWrites=true&w=majority&appName=TicketingSystem
      database: SystemData

server:
  port: 8080

frontend:
  url:
    -https://ticketing-system-wheat.vercel.app/
    -http://localhost:5173